# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from peer import peer_pb2 as peer_dot_peer__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in peer/peer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PeerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Ping = channel.unary_unary(
                '/openhydra.peer.Peer/Ping',
                request_serializer=peer_dot_peer__pb2.PingRequest.SerializeToString,
                response_deserializer=peer_dot_peer__pb2.PingResponse.FromString,
                _registered_method=True)
        self.Forward = channel.unary_unary(
                '/openhydra.peer.Peer/Forward',
                request_serializer=peer_dot_peer__pb2.ForwardRequest.SerializeToString,
                response_deserializer=peer_dot_peer__pb2.ForwardResponse.FromString,
                _registered_method=True)
        self.GetPeerStatus = channel.unary_unary(
                '/openhydra.peer.Peer/GetPeerStatus',
                request_serializer=peer_dot_peer__pb2.PeerStatusRequest.SerializeToString,
                response_deserializer=peer_dot_peer__pb2.PeerStatusResponse.FromString,
                _registered_method=True)
        self.ForwardStream = channel.stream_stream(
                '/openhydra.peer.Peer/ForwardStream',
                request_serializer=peer_dot_peer__pb2.ForwardRequest.SerializeToString,
                response_deserializer=peer_dot_peer__pb2.ForwardResponse.FromString,
                _registered_method=True)
        self.PushResult = channel.unary_unary(
                '/openhydra.peer.Peer/PushResult',
                request_serializer=peer_dot_peer__pb2.ForwardResponse.SerializeToString,
                response_deserializer=peer_dot_peer__pb2.PushAck.FromString,
                _registered_method=True)


class PeerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Ping(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Forward(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPeerStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ForwardStream(self, request_iterator, context):
        """Phase 3A: Bidirectional streaming for persistent sessions.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushResult(self, request, context):
        """Petals parity Phase A: receives final activation from last peer in push chain.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PeerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Ping': grpc.unary_unary_rpc_method_handler(
                    servicer.Ping,
                    request_deserializer=peer_dot_peer__pb2.PingRequest.FromString,
                    response_serializer=peer_dot_peer__pb2.PingResponse.SerializeToString,
            ),
            'Forward': grpc.unary_unary_rpc_method_handler(
                    servicer.Forward,
                    request_deserializer=peer_dot_peer__pb2.ForwardRequest.FromString,
                    response_serializer=peer_dot_peer__pb2.ForwardResponse.SerializeToString,
            ),
            'GetPeerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPeerStatus,
                    request_deserializer=peer_dot_peer__pb2.PeerStatusRequest.FromString,
                    response_serializer=peer_dot_peer__pb2.PeerStatusResponse.SerializeToString,
            ),
            'ForwardStream': grpc.stream_stream_rpc_method_handler(
                    servicer.ForwardStream,
                    request_deserializer=peer_dot_peer__pb2.ForwardRequest.FromString,
                    response_serializer=peer_dot_peer__pb2.ForwardResponse.SerializeToString,
            ),
            'PushResult': grpc.unary_unary_rpc_method_handler(
                    servicer.PushResult,
                    request_deserializer=peer_dot_peer__pb2.ForwardResponse.FromString,
                    response_serializer=peer_dot_peer__pb2.PushAck.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'openhydra.peer.Peer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('openhydra.peer.Peer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Peer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Ping(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openhydra.peer.Peer/Ping',
            peer_dot_peer__pb2.PingRequest.SerializeToString,
            peer_dot_peer__pb2.PingResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Forward(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openhydra.peer.Peer/Forward',
            peer_dot_peer__pb2.ForwardRequest.SerializeToString,
            peer_dot_peer__pb2.ForwardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPeerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openhydra.peer.Peer/GetPeerStatus',
            peer_dot_peer__pb2.PeerStatusRequest.SerializeToString,
            peer_dot_peer__pb2.PeerStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ForwardStream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/openhydra.peer.Peer/ForwardStream',
            peer_dot_peer__pb2.ForwardRequest.SerializeToString,
            peer_dot_peer__pb2.ForwardResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/openhydra.peer.Peer/PushResult',
            peer_dot_peer__pb2.ForwardResponse.SerializeToString,
            peer_dot_peer__pb2.PushAck.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
