# Copyright 2026 OpenHydra contributors — Apache 2.0

"""SpecPipe: Pipeline-filling speculative decoding.

While stage N processes the real token, stages 0..N-1 are idle.
SpecPipe fills those idle stages with speculative future tokens
generated by a local draft model.  Verified tokens emerge at steady
state — one per pipeline cycle, plus accepted speculative tokens.

Reference: arxiv.org/abs/2504.04104 (SpecPipe, April 2025)

Architecture:
    1. Draft model generates K speculative tokens locally (~1ms)
    2. Real token enters stage 0, speculative tokens enter stages 1..K
    3. All stages process concurrently via ThreadPoolExecutor
    4. When real token exits stage N-1, speculative results are verified
    5. Accepted speculative tokens skip remaining stages (already computed)

This is the coordinator-side scheduler.  It uses the existing
InferenceChain._request_stage() for individual stage dispatch
and SwarmSpeculativeDecoder for accept/reject logic.
"""

from __future__ import annotations

import logging
import time
import uuid
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass, field
from typing import Any, Callable

from coordinator.speculative import select_verified_token_ids

logger = logging.getLogger(__name__)


@dataclass(frozen=True)
class SpecPipeConfig:
    """Configuration for the SpecPipe scheduler."""
    enabled: bool = False
    max_speculative_depth: int = 4  # Max concurrent speculative tokens
    draft_timeout_ms: float = 50.0  # Max time for draft model per token
    verify_timeout_ms: float = 5000.0  # Max time per stage verification
    adaptive_enabled: bool = True
    min_depth: int = 1
    max_depth: int = 6
    acceptance_low_watermark: float = 0.40
    acceptance_high_watermark: float = 0.75


@dataclass
class SpecPipeStats:
    """Running statistics for the SpecPipe scheduler."""
    rounds: int = 0
    real_tokens: int = 0
    speculative_dispatched: int = 0
    speculative_accepted: int = 0
    total_stage_calls: int = 0
    total_wall_ms: float = 0.0

    @property
    def acceptance_rate(self) -> float | None:
        if self.speculative_dispatched == 0:
            return None
        return self.speculative_accepted / self.speculative_dispatched

    @property
    def effective_tokens_per_round(self) -> float:
        if self.rounds == 0:
            return 0.0
        return (self.real_tokens + self.speculative_accepted) / self.rounds


@dataclass
class _StageDispatch:
    """A single speculative token dispatched to a pipeline stage."""
    token_id: int
    stage_index: int
    is_real: bool  # True for the primary token, False for speculative
    future: Any = None  # concurrent.futures.Future
    result: list[float] | None = None
    latency_ms: float = 0.0


class SpecPipeScheduler:
    """Concurrent pipeline scheduler for speculative token dispatch.

    Coordinates real + speculative token dispatch across pipeline stages
    using a ThreadPoolExecutor.  The real token flows through ALL stages
    sequentially.  Speculative tokens are dispatched to idle stages
    concurrently.

    Args:
        config: SpecPipe configuration.
        pipeline: Ordered list of pipeline peers (PeerEndpoint objects).
        draft_fn: Callable(context_ids, k) -> list[int] that generates
            k draft token IDs from the context.
        stage_fn: Callable(peer, activation, stage_index, ...) -> list[float]
            that dispatches a single stage via gRPC.
    """

    def __init__(
        self,
        config: SpecPipeConfig,
        pipeline: list,
        draft_fn: Callable[[list[int], int], list[int]],
        stage_fn: Callable[..., list[float]],
    ) -> None:
        self._config = config
        self._pipeline = pipeline
        self._draft_fn = draft_fn
        self._stage_fn = stage_fn
        self._current_depth = config.max_speculative_depth
        self._stats = SpecPipeStats()
        self._executor = ThreadPoolExecutor(
            max_workers=len(pipeline),
            thread_name_prefix="specpipe",
        )

    @property
    def stats(self) -> SpecPipeStats:
        return self._stats

    @property
    def current_depth(self) -> int:
        return self._current_depth

    def run_round(
        self,
        context_ids: list[int],
        prompt: str,
        max_tokens: int = 1,
        request_id: str | None = None,
        kv_session_id: str | None = None,
        **stage_kwargs: Any,
    ) -> list[int]:
        """Execute one SpecPipe round: real token + speculative tokens.

        1. Draft K speculative tokens locally
        2. Dispatch real token (context[-1]) through full pipeline sequentially
        3. Concurrently dispatch speculative tokens to available stages
        4. Verify speculative results against real pipeline output
        5. Return accepted token IDs (real + accepted speculative)

        Args:
            kv_session_id: Session ID for KV cache persistence across rounds.
                When set, each peer caches its KV state and reuses it on
                the next round (avoiding full re-computation of the prompt).

        Returns:
            List of accepted token IDs for this round.
        """
        rid = request_id or str(uuid.uuid4())[:8]
        t_start = time.perf_counter()
        n_stages = len(self._pipeline)

        # 1. Draft K speculative tokens
        k = min(self._current_depth, n_stages - 1, max_tokens)
        if k < 1:
            k = 0
        draft_ids: list[int] = []
        if k > 0:
            try:
                draft_ids = self._draft_fn(context_ids, k)[:k]
            except Exception as exc:
                logger.warning("specpipe_draft_failed: %s", exc)
                draft_ids = []

        # 2. Run the real token through ALL pipeline stages sequentially.
        # Round 0: stage 0 gets the prompt text (for tokenization).
        # Round 1+: stage 0 gets the last token ID as activation (for KV-cached continuation).
        _is_continuation = bool(kv_session_id and self._stats.rounds > 0)
        if _is_continuation and context_ids:
            # Send only the last generated token for KV-cached decode
            real_activation = [float(context_ids[-1])]
            _round_prompt = ""
        else:
            real_activation = []
            _round_prompt = prompt

        real_token_id: int | None = None

        for stage_idx in range(n_stages):
            peer = self._pipeline[stage_idx]
            try:
                real_activation = self._stage_fn(
                    peer=peer,
                    activation=real_activation,
                    prompt=_round_prompt if stage_idx == 0 else "",
                    stage_index=stage_idx,
                    total_stages=n_stages,
                    max_tokens=1 if _is_continuation else max_tokens,
                    request_id=rid,
                    kv_session_id=kv_session_id or "",
                    kv_store_activation=bool(kv_session_id),
                    kv_use_cached_activation=_is_continuation,
                    decode_temperature=0.0,
                    decode_do_sample=False,
                    **stage_kwargs,
                )
                self._stats.total_stage_calls += 1
            except Exception as exc:
                logger.warning("specpipe_real_stage_%d_failed: %s", stage_idx, exc)
                break

        if real_activation:
            real_token_id = int(round(real_activation[0]))
        self._stats.real_tokens += 1

        # 3. Dispatch speculative tokens concurrently through FULL pipeline
        # Each spec token traverses all stages, but different spec tokens
        # run in parallel via the thread pool.
        verified_spec_ids: list[int] = []
        if draft_ids and n_stages > 0:

            def _run_spec_through_pipeline(draft_id: int, spec_idx: int) -> int:
                """Run one speculative token through all pipeline stages."""
                activation = [float(draft_id)]
                # Each spec token gets its own KV session to avoid
                # polluting the real token's cache.
                _spec_kv = f"{kv_session_id}-spec-{spec_idx}" if kv_session_id else ""
                for stage_idx in range(n_stages):
                    peer = self._pipeline[stage_idx]
                    try:
                        activation = self._stage_fn(
                            peer=peer,
                            activation=activation,
                            prompt="" if stage_idx > 0 else prompt,
                            stage_index=stage_idx,
                            total_stages=n_stages,
                            max_tokens=1,
                            request_id=f"{rid}-spec-{spec_idx}",
                            kv_session_id=_spec_kv,
                            kv_store_activation=bool(_spec_kv),
                            kv_use_cached_activation=False,
                            **stage_kwargs,
                        )
                        self._stats.total_stage_calls += 1
                    except Exception as exc:
                        logger.debug("specpipe_spec_stage_%d_failed: %s", stage_idx, exc)
                        return 0
                return int(round(activation[0])) if activation else 0

            spec_futures = []
            for i, draft_id in enumerate(draft_ids):
                fut = self._executor.submit(_run_spec_through_pipeline, draft_id, i)
                spec_futures.append((draft_id, fut))
                self._stats.speculative_dispatched += 1

            for draft_id, fut in spec_futures:
                try:
                    verified_id = fut.result(timeout=self._config.verify_timeout_ms / 1000.0)
                    verified_spec_ids.append(verified_id)
                except Exception:
                    verified_spec_ids.append(0)

        # 4. Accept/reject speculative tokens
        accepted: list[int] = []
        if real_token_id is not None:
            accepted.append(real_token_id)

        if draft_ids and verified_spec_ids:
            selection = select_verified_token_ids(verified_spec_ids, draft_ids)
            accepted.extend(selection.accepted_token_ids)
            # Only count the matched prefix as "accepted" for adaptive depth
            matched = selection.matched_prefix
            self._stats.speculative_accepted += matched

            # Adaptive depth based on matched prefix ratio
            if self._config.adaptive_enabled and draft_ids:
                rate = matched / len(draft_ids)
                if rate >= self._config.acceptance_high_watermark:
                    self._current_depth = min(self._current_depth + 1, self._config.max_depth)
                elif rate < self._config.acceptance_low_watermark:
                    self._current_depth = max(self._current_depth - 1, self._config.min_depth)

        self._stats.rounds += 1
        self._stats.total_wall_ms += (time.perf_counter() - t_start) * 1000

        logger.info(
            "specpipe_round: round=%d real=%s spec_draft=%d spec_accepted=%d depth=%d wall=%.0fms",
            self._stats.rounds,
            real_token_id,
            len(draft_ids),
            len(accepted) - 1,  # subtract real token
            self._current_depth,
            (time.perf_counter() - t_start) * 1000,
        )

        return accepted

    # ------------------------------------------------------------------
    # Pipelined execution: stages process different tokens concurrently
    # ------------------------------------------------------------------

    def run_pipelined(
        self,
        context_ids: list[int],
        prompt: str,
        max_tokens: int = 16,
        request_id: str | None = None,
        kv_session_id: str | None = None,
        **stage_kwargs: Any,
    ) -> list[int]:
        """Generate tokens with overlapped pipeline stages.

        Instead of waiting for a token to traverse all N stages before
        starting the next, each stage runs in its own worker thread with
        an input queue.  After the pipeline fills (N stage latencies),
        one token exits per stage latency — up to N× throughput.

        Flow::

            Stage 0: [T1] [T2] [T3] ...
            Stage 1:      [T1] [T2] ...
            Stage 2:           [T1] ...

        Args:
            context_ids: Initial token context (prompt token IDs).
            prompt: Text prompt for stage 0 on the first token.
            max_tokens: Number of tokens to generate.
            request_id: Correlation ID for logging.
            kv_session_id: KV cache session ID.  Each stage caches its
                past_key_values under this ID for incremental decode.

        Returns:
            List of generated token IDs.
        """
        import queue
        import threading

        rid = request_id or str(uuid.uuid4())[:8]
        n_stages = len(self._pipeline)
        t_start = time.perf_counter()

        # One queue per stage boundary: queue[0] feeds stage 0, queue[N] is output.
        stage_queues: list[queue.Queue] = [queue.Queue(maxsize=4) for _ in range(n_stages + 1)]
        stop_event = threading.Event()

        def _stage_worker(stage_idx: int) -> None:
            """Pull tokens from input queue, process, push to next queue."""
            in_q = stage_queues[stage_idx]
            out_q = stage_queues[stage_idx + 1]
            peer = self._pipeline[stage_idx]
            token_count = 0

            while not stop_event.is_set():
                try:
                    item = in_q.get(timeout=1.0)
                except queue.Empty:
                    continue
                if item is None:  # Poison pill — shutdown
                    out_q.put(None)
                    break

                activation, tok_prompt, is_continuation, tok_idx = item
                try:
                    result = self._stage_fn(
                        peer=peer,
                        activation=activation,
                        prompt=tok_prompt if stage_idx == 0 else "",
                        stage_index=stage_idx,
                        total_stages=n_stages,
                        max_tokens=1,
                        request_id=f"{rid}-t{tok_idx}",
                        kv_session_id=kv_session_id or "",
                        kv_store_activation=bool(kv_session_id),
                        kv_use_cached_activation=is_continuation,
                        decode_temperature=0.0,
                        decode_do_sample=False,
                        **stage_kwargs,
                    )
                    self._stats.total_stage_calls += 1
                    token_count += 1
                    out_q.put((result, tok_idx))
                except Exception as exc:
                    logger.warning(
                        "pipelined_stage_%d_failed: tok=%d err=%s",
                        stage_idx, tok_idx, exc,
                    )
                    out_q.put((None, tok_idx))

        # Start per-stage worker threads
        workers = []
        for s in range(n_stages):
            t = threading.Thread(
                target=_stage_worker, args=(s,),
                name=f"pipe-stage-{s}", daemon=True,
            )
            t.start()
            workers.append(t)

        generated: list[int] = []

        try:
            # Token 0: full prompt (prefill)
            stage_queues[0].put(([], prompt, False, 0))

            for tok_idx in range(max_tokens):
                # Wait for the token to exit the last stage
                item = stage_queues[n_stages].get(timeout=30.0)
                if item is None or item[0] is None:
                    logger.warning("pipelined_token_%d_failed", tok_idx)
                    break

                result_activation, _ = item
                token_id = int(round(result_activation[0]))
                generated.append(token_id)
                self._stats.real_tokens += 1
                self._stats.rounds += 1

                if tok_idx + 1 >= max_tokens:
                    break

                # Feed next token: KV-cached continuation (single token ID)
                stage_queues[0].put(
                    ([float(token_id)], "", True, tok_idx + 1)
                )
        except Exception as exc:
            logger.warning("pipelined_generation_error: %s", exc)
        finally:
            # Send poison pills and wait for workers
            stop_event.set()
            for s in range(n_stages):
                try:
                    stage_queues[s].put(None, timeout=0.5)
                except queue.Full:
                    pass
            for w in workers:
                w.join(timeout=3.0)

        elapsed = time.perf_counter() - t_start
        self._stats.total_wall_ms += elapsed * 1000
        logger.info(
            "pipelined_done: tokens=%d wall=%.0fms tps=%.2f stages=%d",
            len(generated), elapsed * 1000,
            len(generated) / elapsed if elapsed > 0 else 0,
            n_stages,
        )
        return generated

    def shutdown(self) -> None:
        """Shutdown the thread pool."""
        self._executor.shutdown(wait=False)
